<MainWindow>:
    GridLayout:
        cols:1
        size:1000,700
        width:"100dp"
        background:"#00ffce"
        Label:
            text:"Switch "
            font_size:30
            color:"#00ffce"
       
        
        Switch:
            width:"100dp"
            on_active:root.active(self)
        Slider:
            min:0
            max:100
            on_value:root.varr(self)
            value:50
        Label:
            text:root.state
